### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by yonsaber** [Hanse00/CrafTech-old#38] opened 2014-03-10 15:40 UTC
We need to work on cleaning up the code. Looking at it we need to add comments to methods to make it easier to understand what the code is doing. We also need to improve use of things like ID's instead of hard coding values (where we can avoid it).

For example we should change Tileentity to TileEntity.

Also adding helper classes and handlers where we can will provide a huge help.

**Comment by Hanse00** [comment] 2014-03-10 16:51
Pretty much a duplicate of #32, so I'm closing this.

Feel free to continue the discussion over there.

**Closed as completed by Hanse00** 2014-03-10 16:51 UTC
Labels: duplicate, enhancement, code
